#!/bin/bash
# Root user check
if [[ $EUID -ne 0 ]]
then
echo "Error: you must be root to run this command"
exit 1
fi
# Non-empty argument check
if [[ $1 = "" ]]
then
echo "Error: you must provide an argument."
exit 1
fi
if [[ $1 = "--update" ]]
then
  echo "Downloading the latest version of InstallTool..."
  rm $(realpath $0)
  wget -q https://https://raw.githubusercontent.com/denis0001-dev/InstallTool/main/installtool
  chmod +x $(realpath $0)
  echo "Sucessfully updated InstallTool to the latest version."
  exit 0
fi
# Downloading the install script
wget -q https://raw.githubusercontent.com/denis0001-dev/InstallTool/main/$1/install.sh
# Checking for error 404
if [[ $? -eq 8 ]]
then
echo "Error: installation script not found."
exit 1
fi
# Making install script executable
chmod +x install.sh
# Executing the script
./install.sh $2
# Script sucessful run check
if [[ $? -eq 0 ]]
then
echo "Sucessfully installed $1."
exit 0
else
echo "Installation failed with error code $?."
fi
rm install.sh
